extends Node
## Autoload. Port of UIStringTable.cs - English and Italian tables copied
## verbatim from the reference. The reference's Japanese table is mostly
## blank placeholder text, so it's been fully retranslated here from the
## English strings instead of reproducing those gaps.
##
## Spanish, German, French, Portuguese (Brazilian), Russian, and Simplified
## Chinese (not in the reference at all) were added afterward, picked from
## Steam's language-share data as the highest-value languages beyond what's
## already covered here. See UIButtonStyle.gd's fit_button_text/
## fit_menu_button_text for the overflow-safe font-fit system every button/
## label showing these strings routes through.
##
## TABLE rows are sorted alphabetically by each language's own native name
## (Deutsch, English, Español, ...) - LANGUAGE_BY_LOCALE below maps
## OS.get_locale_language() codes to TABLE indices and MUST stay in sync
## with this order (see Game.gd's default-language detection).

enum {
	ID_NEW, ID_ENTER_NAME, ID_OK, ID_CANCEL, ID_BATTLE, ID_SHOP, ID_OPTIONS,
	ID_BACK, ID_PLAY_BATTLE, ID_DECK_SELECT_CARDS, ID_CARDS, ID_FAVORITE_CARDS,
	ID_OPPONENT_SELECT, ID_SELECT, ID_CARD_ATTACK, ID_CARD_TYPE,
	ID_CARD_PHYSICAL_DEFENSE, ID_CARD_MAGICAL_DEFENSE, ID_SKIP, ID_TAKE_ALL,
	ID_CARD_LVLUP, ID_CARD_LVLUP_ATTACK_TYPE, ID_ATTACK_TYPE_PHYSICAL,
	ID_ATTACK_TYPE_MAGICAL, ID_ATTACK_TYPE_FLEXIBLE, ID_ATTACK_TYPE_ASSAULT,
	ID_CARD_LVLUP_MAX, ID_MSG_PICK_1_CARD, ID_MSG_PICK_5_CARD, ID_DONE,
	ID_MSG_CPU_PICK_1_CARD, ID_MSG_CPU_PICK_5_CARD, ID_BATTLE_MENU,
	ID_CARD_STATS, ID_SCORE, ID_COLLECTION, ID_SELL, ID_BUY, ID_BUY_BACK,
	ID_SHOP_HELP, ID_BUY_PRICE, ID_SELL_PRICE, ID_NEED_HELP, ID_MUSIC, ID_SFX,
	ID_CREDITS, ID_DELETE_SLOT_TITLE, ID_DELETE_SLOT_MSG, ID_LANGUAGE,
	ID_BATTLE_END_DRAW, ID_HELP_DECKSELECT1, ID_HELP_DECKSELECT2,
	ID_HELP_DECKSELECT3, ID_HELP_DECKSELECT4, ID_HELP_BATTLE1, ID_HELP_BATTLE2,
	ID_HELP_BATTLE3, ID_HELP_BATTLE4, ID_HELP_BATTLE5, ID_HELP_SHOP1,
	ID_HELP_SHOP2, ID_HELP_SHOP3, ID_HELP_MAIN1, ID_HELP_MAIN2, ID_HELP_MAIN3,
	ID_HELP_MAIN4, ID_HELP_PRESENTATION, ID_HELP_CARDS, ID_OPPONENTS_NAME,
	ID_TAP_TO_START, ID_CLICK_TO_START, ID_TITLE_SCREEN,
	ID_WINS, ID_LAST_SAVED, ID_OWNED, ID_PAGE,
	ID_PAUSE, ID_RESUME, ID_FORFEIT, ID_PAD_TO_START, ID_ADD_REMOVE, ID_SWITCH,
	ID_FAVORITE, ID_CHOOSE, ID_CONFIRM,
	# Online multiplayer.
	ID_ONLINE, ID_LEADERBOARD, ID_SEARCHING_OPPONENT, ID_DECK_POWER,
	ID_OPPONENT_TURN, ID_MATCH_VOIDED, ID_OPPONENT_QUIT, ID_ONLINE_ERROR,
	ID_ONLINE_NO_REWARD, ID_RANK, ID_LOST_BY_QUIT,
	ID_BROWSE,
	ID_RATING, ID_LOSSES,
	# Abbreviated stat captions for the two cramped battle panels. The full
	# forms ("Phys. Verteidigung") are 260px wide at the size those panels now
	# use and have to shrink to 14px to fit 228px of panel - unreadable at any
	# font size, because the limit is the string, not the type size. Shop and
	# Collection have the room and keep the full words.
	ID_CARD_ATTACK_SHORT, ID_CARD_TYPE_SHORT,
	ID_CARD_PDEF_SHORT, ID_CARD_MDEF_SHORT,
	## Online's own play button. Not ID_PLAY_BATTLE ("Play"): here it starts a
	## match against a person, and the word carries that.
	ID_CHALLENGE,
	## Second line of the delete-save confirmation: the online account goes too.
	ID_DELETE_SLOT_ONLINE,
	## Shown on a save another copy of the game currently has open.
	ID_SLOT_IN_USE,
	## Countdown shown once an opponent has been found, before the board opens.
	ID_MATCH_STARTS_IN,
	## "%d cards were taken from you" - carries a count, so it keeps its %d.
	ID_CARDS_LOST,
}

const TABLE := [
	# Deutsch
	[
		"Neu", "Spielernamen eingeben", "OK", "Abbrechen", "Kampf", "Laden",
		"Optionen", "Zurück", "Spielen", "Wähle Fünf Karten", "Karten",
		"Favoriten", "Wähle deinen Gegner", "Auswählen", "Angriff", "Typ",
		"Phys. Verteidigung", "Mag. Verteidigung", "Überspringen", "Alle nehmen",
		"Hoch!", "Neuer Angriffstyp!", "Physisch", "Magisch", "Flexibel",
		"Ansturm", "Max!", "Wähle 1 blaue Karte als Preis",
		"Du hast alle Karten des Gegners gewonnen!", "Fertig",
		"Der Gegner wählt nun eine eroberte Karte als Preis",
		"Der Gegner hat all deine Karten gewonnen...", "MENÜ", "Kartenwerte", "Punkte",
		"Sammlung", "Verkaufen", "Kaufen", "Zurückkaufen!",
		"Ziehe eine Karte in das Feld unten, um sie zu kaufen oder zu verkaufen.",
		"Kaufen", "Verkaufen", "Brauchst du Hilfe? Frag die schwarze Katze!",
		"Musik:", "Effekte:", "Credits", "Slot-Daten löschen",
		"Willst du WIRKLICH ALLE Daten\ndieses Slots löschen?",
		"Sprache:", "Unentschieden, drücke Fertig um fortzufahren.",
		"Dies ist die Deckauswahl. Hier wählst du die Karten aus, mit denen du spielen willst.",
		"Du kannst Karten zwischen der Kartenliste und den Favoriten hin- und herziehen.",
		"Wische vertikal, um den Kartentyp zu wählen, und horizontal, um durch die Karten zu blättern.",
		"Ziehe die Karten in diese Felder, um sie auszuwählen.",
		"Ziehe die Karten auf das Feld, um sie zu spielen", "Hier können keine Karten platziert werden",
		"Verbleibende gegnerische Karten", "Punkte", "Kartenwerte",
		"Ziehe eine Karte hierher, um sie zu verkaufen oder zu kaufen", "Dein Geld",
		"Das ist die Liste der kaufbaren Karten. Weitere Karten werden freigeschaltet, indem du stärkere Gegner besiegst",
		"Kämpfe gegen Gegner, um neue Karten zu gewinnen, sie weiterzuentwickeln und stärkere Feinde freizuschalten",
		"Verkaufe Karten und kaufe neue, um sie im Kampf einzusetzen",
		"Betrachte deine ganze Sammlung in voller Auflösung",
		"Ändere die Spielsprache und stelle die Lautstärke ein. Vergiss nicht, dir die Credits anzusehen ^^",
		"Card Master ist ein Sammelkartenspiel, bei dem zwei Gegner gegeneinander antreten, indem sie Karten auf einem 4x4-Raster platzieren. Jeder Spieler wählt 5 Karten aus seinem Deck. Das Spiel endet, wenn alle Karten platziert sind. Sieger ist, wer am Ende mehr Karten seiner Farbe besitzt. Der Sieger darf sich eine der eroberten gegnerischen Karten stehlen.",
		"Karten haben 4 Werte: Angriff (AT), Typ (T), Physische Verteidigung (PD) und Magische Verteidigung (MD). AT, PD und MD reichen von 0 bis 255, unterteilt in 16 Klassen von 0 bis F. Je höher der Wert, desto höher die Klasse. Eine Karte kann einen von 4 Typen haben: Physisch (P), Magisch (M), Exploit (X) oder Ansturm (A). Jeder Typ bestimmt, wie die Karte gegen andere kämpft. P greift PD an, M greift MD an, X greift den niedrigeren Wert von PD und MD an, A nutzt den höchsten eigenen Wert, um den niedrigsten Wert der gegnerischen Karte anzugreifen, egal welcher das ist. Jede Karte kann bis zu 8 Pfeile haben, die in die 8 Himmelsrichtungen zeigen. Diese Pfeile werden benutzt, um gegnerische Karten zu erobern oder anzugreifen. Zeigt der Pfeil einer Karte auf eine Karte ohne Gegenpfeil, wird diese automatisch erobert; zeigt er auf einen entgegengesetzten Pfeil, beginnt der Kampf. Die Farbe der Werte, von Grün bis Rot, zeigt den Entwicklungsstand. Rot bedeutet, der Wert ist maximal.",
		"Gegner", "Zum Starten tippen", "Zum Starten klicken", "Titel",
		"Siege", "Zuletzt gespeichert", "Besitz", "Seite",
		"Pause", "Fortsetzen", "Aufgeben", "Knopf drücken zum Starten",
		"Hinzu/Weg",
		"Wechseln",
		"Favorit",
		"Wählen",
		"Bestätigen",
		"Online", "Rangliste", "Suche Gegner...", "Deckstärke",
		"Gegner ist am Zug...", "Partie annulliert", "Gegner hat aufgegeben",
		"Keine Verbindung", "Online-Kämpfe bringen kein Geld", "Platz",
		"Durch Aufgeben verloren",
		"Blättern",
		"Wertung", "Niederlagen",
		"Ang.", "Typ", "P.Ver.", "M.Ver.",
		"Herausfordern",
		"Auch dein Online-Konto und deine Ranglistenpunkte werden gelöscht.",
		"Bereits geöffnet",
		"Das Duell beginnt in",
		"%d Karte(n) an Gegner verloren",
	],
	# English
	[
		"New", "Enter Player Name", "OK", "Cancel", "Battle", "Shop", "Options",
		"Back", "Play", "Select Five Cards", "Cards", "Favorite Cards",
		"Select Your Opponent", "Select", "Attack", "Type", "P. Defense",
		"M. Defense", "Skip", "Take All", "Up!", "New Attack Type!", "Physical",
		"Magical", "Flexible", "Assault", "Max!",
		"Choose 1 Blue Card as your Prize",
		"You have won all the opponent's Cards!", "Done",
		"The opponent will now choose a captured Card as his Prize",
		"The opponent has won all your Cards...", "MENU", "Card Stats", "Score",
		"Collection", "Sell", "Buy", "Buy Back!",
		"Move a Card to the box below to buy or sell.", "Buy", "Sell",
		"Need help? Ask the black cat!", "Music:", "SFX:", "Credits",
		"Delete slot data",
		"Are you REALLY sure you want to delete\nALL the data relative to the selected slot?",
		"Language:", "Draw match, press Done to continue.",
		"This is the Deck Select menu. Here you can choose the cards you want use to play.",
		"You can move cards from the Cards list to the Favorite, and vice versa, by dragging them.",
		"Swipe vertically for select the cards type and horizontally for cycle trough the cards.",
		"Drag the cards into these boxes for select them.",
		"Drag the cards in to the grid for play it", "Cards can't be placed here",
		"Opposite remaining cards", "Score", "Card Stats",
		"Move a card here for sell it or buy it", "Your Money",
		"This is the buyable card list. More cards are unlocked by defeating stronger opponents",
		"Fight againts opponents for win new cards, evolve it and unlock stronger foe",
		"Sell cards and buy new one to use it in battle",
		"Watch all your collected cards in full resolution",
		"Change game language and set audio volumes. Don't forget to check out the Credits ^^",
		"Card Master is a collectible cards game, where two opponents fight each other by placing cards in to a 4x4 grid. Every player choose 5 cards of his deck to use. The game end when all the cards are played. The winner is the one that at the end have more cards of his color. The winner player steal one of the captured opponent card.",
		"Cards have 4 stats. Attack (AT), Type (T), Phisical Defense (PD) and Magical Defense (MD). AT, PD and MD value are from 0 to 255, and are subdivided in 16 class from 0 to F. Higher the stats are, higher will be the class. A card can be of 4 Types, Phisical (P), Magical (M), Exploit (X) or Assault (A). Every type define how the card fight againts the other. P attack PD, M attack MD, X attack lowest stats between PD and MD, A use the highest stats of the card to attack the lowest stats of the opponents card, whatever they are. Every crads can have up to 8 arrows, facing the 8 cardinal points. This arrow are used by cards for capture or attack the opponents cards. If a card's arrow face a card without a facing back arrow, the card is automatically captured, but if a card's arrow face a card with a opposite facing back arrow, the fight begin. Stats color, from greens to red, indicate the evolution state of the stats. Red mean the stat is maxed out.",
		"Opponent", "Tap to Start", "Click to Start", "Title",
		"Wins", "Last Saved", "Owned", "Page",
		"Pause", "Resume", "Forfeit", "Press a Button to Start",
		"Add/Remove",
		"Switch",
		"Favorite",
		"Choose",
		"Confirm",
		"Online", "Leaderboard", "Looking for an opponent...", "Deck Power",
		"Opponent's turn...", "Match voided", "The opponent quit",
		"No connection", "Online battles earn no coins", "Rank",
		"Lost by quitting",
		"Browse",
		"Rating", "Losses",
		"Atk", "Type", "P.Def", "M.Def",
		"Challenge",
		"Your online account and leaderboard score are deleted as well.",
		"Already open",
		"The challenge begins in",
		"%d card(s) taken by opponents",
	],
	# Español
	[
		"Nuevo", "Introduce el Nombre del Jugador", "OK", "Cancelar", "Batalla",
		"Tienda", "Opciones", "Atrás", "Jugar", "Elige Cinco Cartas", "Cartas",
		"Cartas Favoritas", "Elige a tu Oponente", "Elegir", "Ataque", "Tipo",
		"Def. Física", "Def. Mágica", "Saltar", "Llevar Todas", "¡Sube!",
		"¡Nuevo Tipo de Ataque!", "Física", "Mágica", "Flexible", "Asalto",
		"¡Máx!", "Elige 1 Carta Azul como Premio",
		"¡Has ganado todas las cartas del oponente!", "Hecho",
		"El oponente elegirá ahora una Carta capturada como Premio",
		"El oponente ha ganado todas tus cartas...", "MENÚ", "Estadísticas", "Puntos",
		"Colección", "Vender", "Comprar", "¡Recomprar!",
		"Mueve una carta al recuadro de abajo para comprar o vender.",
		"Comprar", "Vender", "¿Necesitas ayuda? ¡Pregúntale al gato negro!",
		"Música:", "Efectos:", "Créditos", "Borrar datos del slot",
		"¿Estás REALMENTE seguro de que quieres borrar\nTODOS los datos de este slot?",
		"Idioma:", "Empate, pulsa Hecho para continuar.",
		"Este es el menú de Selección de Mazo. Aquí puedes elegir las cartas que quieres usar para jugar.",
		"Puedes mover cartas entre la lista de Cartas y Favoritas, y viceversa, arrastrándolas.",
		"Desliza verticalmente para elegir el tipo de carta y horizontalmente para recorrer las cartas.",
		"Arrastra las cartas a estos recuadros para seleccionarlas.",
		"Arrastra las cartas a la cuadrícula para jugarlas", "No se pueden colocar cartas aquí",
		"Cartas restantes del rival", "Puntos", "Estadísticas",
		"Mueve una carta aquí para venderla o comprarla", "Tu Dinero",
		"Esta es la lista de cartas disponibles. Se desbloquean más cartas al derrotar rivales más fuertes",
		"Enfréntate a rivales para ganar cartas nuevas, evolucionarlas y desbloquear enemigos más fuertes",
		"Vende cartas y compra otras nuevas para usarlas en batalla",
		"Contempla toda tu colección de cartas en alta resolución",
		"Cambia el idioma del juego y ajusta el volumen. ¡No olvides echar un vistazo a los Créditos! ^^",
		"Card Master es un juego de cartas coleccionables, donde dos jugadores se enfrentan colocando cartas en una cuadrícula de 4x4. Cada jugador elige 5 cartas de su mazo para usar. La partida termina cuando se han colocado todas las cartas. El ganador es quien al final tiene más cartas de su color. El jugador ganador roba una de las cartas capturadas al oponente.",
		"Las cartas tienen 4 estadísticas: Ataque (AT), Tipo (T), Defensa Física (DF) y Defensa Mágica (DM). Los valores de AT, DF y DM van de 0 a 255, divididos en 16 clases de 0 a F. Cuanto más alta la estadística, más alta será la clase. Una carta puede ser de 4 tipos: Física (P), Mágica (M), Exploit (X) o Asalto (A). Cada tipo define cómo lucha la carta contra las demás. P ataca DF, M ataca DM, X ataca la estadística más baja entre DF y DM, A usa la estadística más alta de la carta para atacar la más baja de la carta rival, sea cual sea. Cada carta puede tener hasta 8 flechas, orientadas hacia los 8 puntos cardinales. Estas flechas se usan para capturar o atacar cartas rivales. Si la flecha de una carta apunta a una carta sin flecha de vuelta, la carta es capturada automáticamente, pero si apunta a una carta con flecha opuesta, comienza el combate. El color de las estadísticas, de verde a rojo, indica su nivel de evolución. El rojo significa que la estadística está al máximo.",
		"Rival", "Toca para empezar", "Haz clic para empezar", "Título",
		"Victorias", "Último guardado", "Poseídas", "Página",
		"Pausa", "Reanudar", "Rendirse", "Pulsa un botón para empezar",
		"Añadir/Quitar",
		"Cambiar",
		"Favorita",
		"Elegir",
		"Confirmar",
		"En línea", "Clasificación", "Buscando rival...", "Poder del mazo",
		"Turno del rival...", "Partida anulada", "El rival ha abandonado",
		"Sin conexión", "Los combates en línea no dan monedas", "Puesto",
		"Perdida por abandono",
		"Explorar",
		"Puntuación", "Derrotas",
		"Ata.", "Tipo", "D.Fis.", "D.Mag.",
		"Desafiar",
		"También se borran tu cuenta en línea y tu puntuación.",
		"Ya está abierto",
		"El desafío empieza en",
		"%d carta(s) ganada(s) por rivales",
	],
	# Français
	[
		"Nouveau", "Entrez le nom du joueur", "OK", "Annuler", "Combat",
		"Boutique", "Options", "Retour", "Jouer", "Choisissez cinq cartes",
		"Cartes", "Cartes favorites", "Choisissez votre adversaire", "Sélectionner",
		"Attaque", "Type", "Déf. physique", "Déf. magique", "Passer",
		"Tout prendre", "En hausse !", "Nouveau type d'attaque !", "Physique",
		"Magique", "Flexible", "Assaut", "Max !",
		"Choisissez 1 carte bleue comme récompense",
		"Vous avez gagné toutes les cartes de l'adversaire !", "Terminé",
		"L'adversaire va maintenant choisir une carte capturée comme récompense",
		"L'adversaire a gagné toutes vos cartes...", "MENU", "Statistiques", "Score",
		"Collection", "Vendre", "Acheter", "Racheter !",
		"Déplacez une carte dans la case ci-dessous pour l'acheter ou la vendre.",
		"Acheter", "Vendre", "Besoin d'aide ? Demandez au chat noir !",
		"Musique :", "Effets :", "Crédits", "Supprimer les données du slot",
		"Voulez-vous VRAIMENT supprimer\nTOUTES les données de ce slot ?",
		"Langue :", "Match nul, appuyez sur Terminé pour continuer.",
		"Ceci est le menu de sélection du deck. Ici, vous choisissez les cartes que vous voulez utiliser pour jouer.",
		"Vous pouvez déplacer des cartes entre la liste des cartes et les favoris, et inversement, en les faisant glisser.",
		"Faites glisser verticalement pour choisir le type de carte et horizontalement pour parcourir les cartes.",
		"Faites glisser les cartes dans ces cases pour les sélectionner.",
		"Faites glisser les cartes sur la grille pour les jouer", "Les cartes ne peuvent pas être placées ici",
		"Cartes restantes de l'adversaire", "Score", "Statistiques",
		"Déplacez une carte ici pour la vendre ou l'acheter", "Votre argent",
		"Voici la liste des cartes disponibles à l'achat. D'autres cartes se débloquent en battant des adversaires plus forts",
		"Affrontez des adversaires pour gagner de nouvelles cartes, les faire évoluer et débloquer des ennemis plus forts",
		"Vendez des cartes et achetez-en de nouvelles à utiliser au combat",
		"Admirez toute votre collection de cartes en haute résolution",
		"Changez la langue du jeu et réglez le volume. N'oubliez pas de consulter les crédits ^^",
		"Card Master est un jeu de cartes à collectionner, où deux adversaires s'affrontent en plaçant des cartes sur une grille 4x4. Chaque joueur choisit 5 cartes de son deck à utiliser. La partie se termine quand toutes les cartes sont placées. Le vainqueur est celui qui possède le plus de cartes de sa couleur à la fin. Le joueur vainqueur vole une des cartes capturées à l'adversaire.",
		"Les cartes ont 4 statistiques : Attaque (AT), Type (T), Défense Physique (DP) et Défense Magique (DM). Les valeurs d'AT, DP et DM vont de 0 à 255, réparties en 16 classes de 0 à F. Plus la statistique est élevée, plus la classe l'est aussi. Une carte peut être de 4 types : Physique (P), Magique (M), Exploit (X) ou Assaut (A). Chaque type définit comment la carte combat les autres. P attaque DP, M attaque DM, X attaque la statistique la plus faible entre DP et DM, A utilise la statistique la plus élevée de la carte pour attaquer la plus faible de la carte adverse, quelle qu'elle soit. Chaque carte peut avoir jusqu'à 8 flèches, orientées vers les 8 points cardinaux. Ces flèches servent à capturer ou attaquer les cartes adverses. Si la flèche d'une carte pointe vers une carte sans flèche opposée, la carte est automatiquement capturée ; mais si elle pointe vers une flèche opposée, le combat commence. La couleur des statistiques, du vert au rouge, indique leur niveau d'évolution. Le rouge signifie que la statistique est au maximum.",
		"Adversaire", "Touchez pour commencer", "Cliquez pour commencer", "Titre",
		"Victoires", "Dernière sauvegarde", "Possédées", "Page",
		"Pause", "Reprendre", "Abandonner", "Appuyez sur un bouton pour commencer",
		"Ajout/Retrait",
		"Changer",
		"Favori",
		"Choisir",
		"Confirmer",
		"En ligne", "Classement", "Recherche d'un adversaire...", "Puissance du deck",
		"Tour de l'adversaire...", "Partie annulée", "L'adversaire a abandonné",
		"Pas de connexion", "Les combats en ligne ne rapportent pas d'argent", "Rang",
		"Perdue par abandon",
		"Parcourir",
		"Score", "Défaites",
		"Att.", "Type", "Def.P.", "Def.M.",
		"Défier",
		"Ton compte en ligne et ton classement seront également supprimés.",
		"Déjà ouvert",
		"Le défi commence dans",
		"%d carte(s) prise(s) par des adversaires",
	],
	# Italiano
	[
		"Nuovo", "Inserisci il nome del giocatore", "OK", "Annulla", "Battaglia",
		"Negozio", "Opzioni", "Indietro", "Gioca", "Seleziona Cinque Carte",
		"Carte", "Carte Preferite", "Seleziona il Tuo Avversario", "Seleziona",
		"Attacco", "Tipo", "Dif. Fisica", "Dif. Magica", "Skippa", "Prendi Tutte",
		"Up!", "Nuovo Attack Type!", "Fisico", "Magico", "Flessibile", "Assalto",
		"Max!", "Seleziona una Carta Blu come Premio",
		"Hai vinto tutte le carte del tuo avversario!", "Continua",
		"L'avversario scegliera' una Carta catturata come Premio",
		"L'avversario ha vinto tutte le tue carte...", "MENU", "Statistiche Carta",
		"Punti", "Collezione", "Vendi", "Compra", "Ricompra!",
		"Sposta le carte nel riquadro in basso per comprare o vendere.",
		"Compra", "Vendi", "Serve aiuto? Chiedi al gatto!", "Musica:",
		"Effetti:", "Crediti", "Cancellazione Dati Slot",
		"Sei DAVVERO sicuro di voler cancellare\nTUTTI i dati relativi allo slot selezionato?",
		"Lingua:", "Partita Pareggiata, premi Continua per continuare.",
		"Questo é il Deck Menu. Qui puoi scegliere quali carte usare per giocare.",
		"Puoi spostare le carte dalla lista ai preferiti, e vice versa, trascinandole.",
		"Scorri verticalmente per cambiare il tipo di carta e orizzontalmente per scorrere le carte.",
		"Trascina le carte nel riquadro per selezionarle.",
		"Trascina le carte nella griglia per giocarle",
		"Le carte non possno essere giocate sui blocci",
		"Carte rimanenti dell'avversario", "Punteggio", "Statistiche Carta",
		"Posiziona la carta qui per venderla o comprarla", "Monete possedute",
		"Questa é la lista delle carte acquistabili. Si sbloccano nuove carte sconfiggendo avversari piú forti",
		"Combatti gli avversari per conquistare nuove carte, potenziarle e sbloccare nuovi sfidanti",
		"Vendi e compra nuove carte da usare in battaglia",
		"Ammira la tua collezione di carte in alta risoluzione",
		"Cambia la lingua di gioco e modifica i volumi audio. Non dimenticarti di guadare i Crediti ^^",
		"Card Master é un gioco di carte collezionabili, dove 2 avversari si sfidano posizionando delle carte su una griglia 4x4. Ogni giocatore sceglie 5 carte tra tutte quelle possedute. Il gioco termina quando tutte le carte di entrambi i giocatori vengono posizionate. Il vincitore é colui che a fine partita possiede piú carte del suo colore. Il giocatore vincente puó sottrarre all'avversario una carta catturata durante la partita.",
		"Le carte hanno 4 valori. Attacco (AT), Tipo (T), Difesa Fisica (DF) e Difesa Magica (DM). AT, DF e DM hanno valori che vanno tra 0 e 255, suddivisi in 16 classi da 0 a F. Piú il valore é alto, piú la classe sará elevata. Una carta puó essere di 4 tipi, Fisica (P), Magica (M), Exploit (X) e Assalto (A). P attacca DF, M attacca DM, X attacca il valore piú basso tra DF e DM e A usa il valore piú alto della carta per attaccare quello piú basso di quella avversaria. Ogni carta puó avere fino a 8 frecce posizionate sui punti cardinali. Queste frecce vengono utilizzate per catturare o attaccare le carte avversarie. Se la freccia di una carta punta una carta che non ha a sua volta una freccia nella direzione opposta, essa viene automaticamente catturata, altrimenti se c'é una freccia opposta, ha inizio il combattimento. Il colore delle statistiche indica il livello di evoluzione delle stesse. Il colore rosso indica una statistica che ha raggiunto il suo massimo per quel tipo di carta.",
		"Avversario", "Tocca per iniziare", "Clicca per iniziare", "Titolo",
		"Vittorie", "Ultimo salvataggio", "Possedute", "Pagina",
		"Pausa", "Riprendi", "Abbandona", "Premi un tasto per iniziare",
		"Aggiungi/Rimuovi",
		"Cambia",
		"Preferita",
		"Scegli",
		"Conferma",
		"Online", "Classifica", "Ricerca avversario...", "Potere del mazzo",
		"Turno dell'avversario...", "Partita annullata", "L'avversario ha abbandonato",
		"Nessuna connessione", "Le sfide online non danno monete", "Posizione",
		"Persa per abbandono",
		"Sfoglia",
		"Punteggio", "Perse",
		"Att.", "Tipo", "Dif.F.", "Dif.M.",
		"Sfida",
		"Verranno cancellati anche il tuo account online e il tuo punteggio.",
		"Già aperto",
		"La sfida inizierà tra",
		"%d carta/e vinta/e dagli avversari",
	],
	# Português (Brasil)
	[
		"Novo", "Digite o Nome do Jogador", "OK", "Cancelar", "Batalha", "Loja",
		"Opções", "Voltar", "Jogar", "Selecione Cinco Cartas", "Cartas",
		"Cartas Favoritas", "Selecione seu Adversário", "Selecionar", "Ataque",
		"Tipo", "Def. Física", "Def. Mágica", "Pular", "Pegar Todas", "Subiu!",
		"Novo Tipo de Ataque!", "Física", "Mágica", "Flexível", "Investida",
		"Máx!", "Escolha 1 Carta Azul como Prêmio",
		"Você ganhou todas as cartas do adversário!", "Concluído",
		"O adversário agora vai escolher uma Carta capturada como Prêmio",
		"O adversário ganhou todas as suas cartas...", "MENU", "Estatísticas", "Pontuação",
		"Coleção", "Vender", "Comprar", "Recomprar!",
		"Mova uma carta para a caixa abaixo para comprar ou vender.",
		"Comprar", "Vender", "Precisa de ajuda? Pergunte ao gato preto!",
		"Música:", "Efeitos:", "Créditos", "Apagar dados do slot",
		"Você tem CERTEZA de que quer apagar\nTODOS os dados deste slot?",
		"Idioma:", "Empate, pressione Concluído para continuar.",
		"Este é o menu de Seleção de Deck. Aqui você escolhe as cartas que quer usar para jogar.",
		"Você pode mover cartas entre a lista de Cartas e Favoritas, e vice-versa, arrastando-as.",
		"Deslize verticalmente para escolher o tipo de carta e horizontalmente para percorrer as cartas.",
		"Arraste as cartas para estas caixas para selecioná-las.",
		"Arraste as cartas para a grade para jogá-las", "As cartas não podem ser colocadas aqui",
		"Cartas restantes do adversário", "Pontuação", "Estatísticas",
		"Mova uma carta aqui para vendê-la ou comprá-la", "Seu Dinheiro",
		"Esta é a lista de cartas disponíveis para compra. Mais cartas são desbloqueadas ao derrotar adversários mais fortes",
		"Enfrente adversários para ganhar cartas novas, evoluí-las e desbloquear inimigos mais fortes",
		"Venda cartas e compre outras novas para usar na batalha",
		"Admire toda a sua coleção de cartas em alta resolução",
		"Mude o idioma do jogo e ajuste o volume. Não esqueça de conferir os Créditos ^^",
		"Card Master é um jogo de cartas colecionáveis, onde dois adversários se enfrentam colocando cartas em uma grade 4x4. Cada jogador escolhe 5 cartas do seu deck para usar. O jogo termina quando todas as cartas forem colocadas. O vencedor é quem tiver mais cartas da sua cor ao final. O jogador vencedor rouba uma das cartas capturadas do adversário.",
		"As cartas têm 4 estatísticas: Ataque (AT), Tipo (T), Defesa Física (DF) e Defesa Mágica (DM). Os valores de AT, DF e DM vão de 0 a 255, divididos em 16 classes de 0 a F. Quanto maior a estatística, maior a classe. Uma carta pode ser de 4 tipos: Física (P), Mágica (M), Exploit (X) ou Investida (A). Cada tipo define como a carta luta contra as outras. P ataca DF, M ataca DM, X ataca o menor valor entre DF e DM, A usa o maior valor da carta para atacar o menor valor da carta adversária, seja qual for. Cada carta pode ter até 8 setas, apontando para os 8 pontos cardeais. Essas setas são usadas para capturar ou atacar cartas adversárias. Se a seta de uma carta aponta para uma carta sem seta de volta, a carta é capturada automaticamente; mas se aponta para uma seta oposta, a batalha começa. A cor das estatísticas, do verde ao vermelho, indica o nível de evolução. Vermelho significa que a estatística está no máximo.",
		"Adversário", "Toque para começar", "Clique para começar", "Título",
		"Vitórias", "Último salvamento", "Possuídas", "Página",
		"Pausa", "Continuar", "Desistir", "Pressione um botão para começar",
		"Adicionar/Remover",
		"Trocar",
		"Favorita",
		"Escolher",
		"Confirmar",
		"Online", "Classificação", "Procurando adversário...", "Poder do baralho",
		"Vez do adversário...", "Partida anulada", "O adversário desistiu",
		"Sem conexão", "Batalhas online não dão moedas", "Posição",
		"Perdida por desistência",
		"Navegar",
		"Pontuação", "Derrotas",
		"Ata.", "Tipo", "Def.F.", "Def.M.",
		"Desafiar",
		"Sua conta online e sua pontuação também serão apagadas.",
		"Já está aberto",
		"O desafio começa em",
		"%d carta(s) levada(s) por adversários",
	],
	# Русский
	[
		"Новый", "Введите имя игрока", "ОК", "Отмена", "Битва", "Магазин",
		"Настройки", "Назад", "Играть", "Выберите пять карт", "Карты",
		"Избранные карты", "Выберите противника", "Выбрать", "Атака", "Тип",
		"Физ. защита", "Маг. защита", "Пропустить", "Забрать все", "Улучшение!",
		"Новый тип атаки!", "Физический", "Магический", "Гибкий", "Штурм",
		"Макс!", "Выберите 1 синюю карту в награду",
		"Вы выиграли все карты соперника!", "Готово",
		"Теперь соперник выберет захваченную карту в награду",
		"Соперник выиграл все ваши карты...", "МЕНЮ", "Характеристики", "Счёт",
		"Коллекция", "Продать", "Купить", "Выкупить!",
		"Переместите карту в поле ниже, чтобы купить или продать.",
		"Купить", "Продать", "Нужна помощь? Спросите чёрного кота!",
		"Музыка:", "Звук:", "Титры", "Удалить данные слота",
		"Вы ДЕЙСТВИТЕЛЬНО хотите удалить\nВСЕ данные этого слота?",
		"Язык:", "Ничья, нажмите «Готово», чтобы продолжить.",
		"Это меню выбора колоды. Здесь вы выбираете карты, которыми хотите играть.",
		"Вы можете перетаскивать карты между списком карт и избранным в обе стороны.",
		"Проведите вертикально, чтобы выбрать тип карт, и горизонтально, чтобы листать карты.",
		"Перетащите карты в эти поля, чтобы выбрать их.",
		"Перетащите карты на сетку, чтобы сыграть ими", "Сюда нельзя поместить карты",
		"Оставшиеся карты соперника", "Счёт", "Характеристики",
		"Переместите карту сюда, чтобы продать или купить её", "Ваши деньги",
		"Это список карт, доступных для покупки. Больше карт открывается за победу над более сильными противниками",
		"Сражайтесь с противниками, чтобы получать новые карты, развивать их и открывать более сильных врагов",
		"Продавайте карты и покупайте новые, чтобы использовать их в бою",
		"Просмотрите всю свою коллекцию карт в полном разрешении",
		"Смените язык игры и настройте громкость звука. Не забудьте заглянуть в титры ^^",
		"Card Master — это игра в коллекционные карты, где два игрока сражаются, размещая карты на сетке 4x4. Каждый игрок выбирает 5 карт из своей колоды. Игра заканчивается, когда все карты выставлены. Победителем становится тот, у кого в итоге больше карт своего цвета. Победитель забирает одну из захваченных карт соперника.",
		"У карт есть 4 характеристики: Атака (AT), Тип (T), Физическая защита (PD) и Магическая защита (MD). Значения AT, PD и MD варьируются от 0 до 255 и делятся на 16 классов от 0 до F. Чем выше значение, тем выше класс. Карта может быть одного из 4 типов: Физический (P), Магический (M), Эксплойт (X) или Штурм (A). Каждый тип определяет, как карта сражается с другими. P атакует PD, M атакует MD, X атакует более низкое значение из PD и MD, A использует самое высокое значение карты, чтобы атаковать самое низкое значение карты противника, каким бы оно ни было. У каждой карты может быть до 8 стрелок, направленных по 8 сторонам света. Эти стрелки используются для захвата или атаки карт противника. Если стрелка карты направлена на карту без ответной стрелки, карта захватывается автоматически, а если стрелка направлена на противоположную стрелку — начинается бой. Цвет характеристик, от зелёного до красного, показывает уровень их развития. Красный означает, что характеристика достигла максимума.",
		"Соперник", "Коснитесь, чтобы начать", "Нажмите, чтобы начать", "Заставка",
		"Победы", "Последнее сохранение", "В наличии", "Страница",
		"Пауза", "Продолжить", "Сдаться", "Нажмите любую кнопку, чтобы начать",
		"Добавить/Убрать",
		"Сменить",
		"Избранная",
		"Выбрать",
		"Подтвердить",
		"Онлайн", "Таблица лидеров", "Поиск соперника...", "Сила колоды",
		"Ход соперника...", "Матч аннулирован", "Соперник вышел из игры",
		"Нет соединения", "Онлайн-бои не приносят монет", "Место",
		"Поражение из-за выхода",
		"Просмотр",
		"Рейтинг", "Поражения",
		"Атк.", "Тип", "Ф.Защ.", "М.Защ.",
		"Вызов",
		"Ваш онлайн-аккаунт и место в таблице лидеров также будут удалены.",
		"Уже открыт",
		"Матч начнётся через",
		"Соперники забрали карт: %d",
	],
	# 日本語 - full retranslation from English (the reference table was mostly
	# blank placeholders).
	[
		"新規", "プレイヤー名を入力", "OK", "キャンセル", "バトル", "ショップ",
		"オプション", "戻る", "プレイ", "カードを5枚選択", "カード",
		"お気に入りカード", "対戦相手を選択", "選択", "攻撃", "種類", "物理防御",
		"魔法防御", "スキップ", "全て取る", "アップ!", "新しい攻撃タイプ!", "物理",
		"魔法", "柔軟", "強襲", "マックス!", "賞品として青いカードを1枚選んでください",
		"相手のカードを全て獲得しました!", "完了",
		"対戦相手が捕獲したカードを賞品として選びます",
		"対戦相手があなたのカードを全て獲得しました...", "メニュー", "カードステータス",
		"スコア", "コレクション", "売る", "買う", "買い戻す!",
		"カードを下の枠に移動して売買してください。", "購入", "売却",
		"助けが必要?黒猫に聞いてみて!", "音楽:", "効果音:", "クレジット",
		"スロットデータを削除",
		"選択したスロットの\n全てのデータを本当に削除しますか?",
		"言語:", "引き分けです。続けるには完了を押してください。",
		"ここはデッキ選択メニューです。使用したいカードを選ぶことができます。",
		"カードリストとお気に入りの間で、ドラッグしてカードを移動できます。",
		"縦にスワイプでカードの種類を選択、横にスワイプでカードを切り替えます。",
		"カードをこの枠にドラッグして選択してください。",
		"カードをグリッドにドラッグしてプレイします", "ここにはカードを置けません",
		"相手の残りカード", "スコア", "カードステータス",
		"売買するにはカードをここに移動してください", "所持金",
		"これは購入可能なカードのリストです。強い相手を倒すとさらにカードが解放されます",
		"対戦相手と戦って新しいカードを獲得し、進化させて強い敵を解放しよう",
		"カードを売って、バトルで使う新しいカードを買おう",
		"集めたカードを高解像度で鑑賞できます",
		"ゲームの言語変更や音量設定ができます。クレジットも忘れずにチェックしてね^^",
		"「カードマスター」は、2人のプレイヤーが4x4のグリッドにカードを置いて戦うカード収集ゲームです。各プレイヤーはデッキから使用する5枚のカードを選びます。全てのカードが置かれるとゲームは終了します。最終的に自分の色のカードを多く持っている方が勝利です。勝者は捕獲した相手のカードを1枚奪うことができます。",
		"カードには4つのステータスがあります。攻撃力(AT)、タイプ(T)、物理防御力(PD)、魔法防御力(MD)です。AT、PD、MDの値は0〜255で、0〜Fの16段階に分けられます。数値が高いほどクラスも高くなります。カードには物理(P)、魔法(M)、万能(X)、強襲(A)の4つのタイプがあり、タイプによって戦い方が決まります。Pの攻撃はPDを、Mの攻撃はMDを狙います。XはPDとMDのうち低い方を狙い、Aはカードの最も高いステータスで相手の最も低いステータスを攻撃します。カードには8方向に矢印を最大8個まで持てます。この矢印は相手のカードを捕獲したり攻撃したりするために使われます。矢印が反対方向の矢印を持たないカードを指している場合、そのカードは自動的に捕獲されます。逆に反対方向に矢印があると戦闘が始まります。ステータスの色は緑から赤へと進化状態を示し、赤は最大値に達したことを意味します。",
		"対戦相手", "タップしてスタート", "クリックしてスタート", "タイトル",
		"勝利数", "最終セーブ", "所持数", "ページ",
		"ポーズ", "再開", "棄権", "ボタンを押してスタート",
		"追加/削除",
		"切替",
		"お気に入り",
		"選ぶ",
		"確定",
		"オンライン", "ランキング", "対戦相手を探しています...", "デッキパワー",
		"相手のターン...", "対戦は無効になりました", "相手が退出しました",
		"接続できません", "オンライン対戦ではお金を獲得できません", "順位",
		"途中退出により敗北",
		"閲覧",
		"レート", "敗北",
		"攻撃", "種類", "物防", "魔防",
		"対戦",
		"オンラインアカウントとランキングの記録も削除されます。",
		"使用中",
		"対戦開始まで",
		"相手に奪われたカード: %d枚",
	],
	# 简体中文
	[
		"新建", "输入玩家名称", "确定", "取消", "对战", "商店", "设置", "返回",
		"开始", "选择五张卡牌", "卡牌", "收藏卡牌", "选择对手", "选择", "攻击",
		"类型", "物理防御", "魔法防御", "跳过", "全部拿走", "提升!", "新攻击类型!",
		"物理", "魔法", "灵活", "突袭", "已满级!", "选择1张蓝色卡牌作为奖励",
		"你赢得了对手的所有卡牌!", "完成", "对手现在将选择一张被俘获的卡牌作为奖励",
		"对手赢得了你的所有卡牌…", "菜单", "卡牌属性", "分数", "收藏", "出售",
		"购买", "买回!", "将卡牌拖到下方的框中以购买或出售。", "购买", "出售",
		"需要帮助?问问黑猫吧!", "音乐:", "音效:", "制作人员", "删除存档数据",
		"你真的确定要删除\n所选存档槽的所有数据吗?",
		"语言:", "平局,按\"完成\"继续。",
		"这是选卡界面。在这里你可以选择想要用来对战的卡牌。",
		"你可以通过拖动,在卡牌列表和收藏之间来回移动卡牌。",
		"垂直滑动可选择卡牌类型,水平滑动可切换卡牌。",
		"将卡牌拖入这些框中以选择它们。",
		"将卡牌拖到网格中以使用它", "此处无法放置卡牌",
		"对手剩余卡牌", "分数", "卡牌属性",
		"将卡牌移到这里以出售或购买", "你的金币",
		"这是可购买的卡牌列表。击败更强的对手可解锁更多卡牌",
		"与对手战斗以赢得新卡牌,进化它们并解锁更强的敌人",
		"出售卡牌,购买新卡牌用于对战",
		"以全分辨率欣赏你收藏的所有卡牌",
		"更改游戏语言并设置音量。别忘了看看制作人员名单哦 ^^",
		"《卡牌大师》是一款集换式卡牌游戏,两名玩家通过在4x4的格子上放置卡牌来对战。每位玩家从自己的牌组中选择5张卡牌使用。当所有卡牌都放置完毕时游戏结束。最终拥有更多自己颜色卡牌的一方获胜。获胜的玩家可以夺走一张被俘获的对手卡牌。",
		"卡牌有4项属性:攻击(AT)、类型(T)、物理防御(PD)和魔法防御(MD)。AT、PD和MD的数值范围是0到255,分为从0到F的16个等级。数值越高,等级越高。卡牌有4种类型:物理(P)、魔法(M)、万能(X)或突袭(A)。每种类型决定了卡牌如何与其他卡牌对战。P攻击PD,M攻击MD,X攻击PD和MD中较低的一项,A使用卡牌中最高的属性攻击对方卡牌中最低的属性,无论那是哪一项。每张卡牌最多可以有8个箭头,分别指向8个方位。这些箭头用于俘获或攻击对手的卡牌。如果一张卡牌的箭头指向一张没有对应反向箭头的卡牌,该卡牌会被自动俘获;但如果指向的是有相对箭头的卡牌,则会触发战斗。属性的颜色从绿到红表示其进化程度,红色表示该属性已达到最大值。",
		"对手", "轻触开始", "点击开始", "标题",
		"胜场", "最后保存", "拥有", "页",
		"暂停", "继续", "认输", "按任意键开始",
		"添加/移除",
		"切换",
		"收藏",
		"选择",
		"确认",
		"在线", "排行榜", "正在寻找对手...", "卡组强度",
		"对手的回合...", "本局已作废", "对手已退出",
		"无法连接", "在线对战不会获得金币", "排名",
		"因退出而判负",
		"浏览",
		"积分", "败场",
		"攻击", "类型", "物防", "法防",
		"挑战",
		"你的在线账号和排行榜成绩也会一并删除。",
		"已在使用",
		"对战开始还有",
		"被对手夺走的卡牌: %d 张",
	],
]

## Maps OS.get_locale_language() codes to TABLE indices - must stay in sync
## with TABLE's order above. Used by Game.gd to default to the system
## language on first launch (before any language has been explicitly saved).
const LANGUAGE_BY_LOCALE := {
	"de": 0, "en": 1, "es": 2, "fr": 3, "it": 4, "pt": 5, "ru": 6, "ja": 7, "zh": 8,
}
const DEFAULT_LANGUAGE := 1  # English - used when the system locale isn't one of the above

func get_string(id: int) -> String:
	return TABLE[Game.language][id]
