extends Node
## Autoload. Port of UIStringTable.cs - English and Italian tables copied
## verbatim from the reference. The reference's Japanese table is mostly
## blank placeholder text, so it's been fully retranslated here from the
## English strings instead of reproducing those gaps.

enum {
	ID_NEW, ID_ENTER_NAME, ID_OK, ID_CANCEL, ID_BATTLE, ID_SHOP, ID_OPTIONS,
	ID_BACK, ID_PLAY_BATTLE, ID_DECK_SELECT_CARDS, ID_CARDS, ID_FAVORITE_CARDS,
	ID_OPPONENT_SELECT, ID_SELECT, ID_CARD_ATTACK, ID_CARD_TYPE,
	ID_CARD_PHYSICAL_DEFENSE, ID_CARD_MAGICAL_DEFENSE, ID_SKIP, ID_TAKE_ALL,
	ID_CARD_LVLUP, ID_CARD_LVLUP_ATTACK_TYPE, ID_ATTACK_TYPE_PHYSICAL,
	ID_ATTACK_TYPE_MAGICAL, ID_ATTACK_TYPE_FLEXIBLE, ID_ATTACK_TYPE_ASSAULT,
	ID_CARD_LVLUP_MAX, ID_MSG_PICK_1_CARD, ID_MSG_PICK_5_CARD, ID_DONE,
	ID_MSG_CPU_PICK_1_CARD, ID_MSG_CPU_PICK_5_CARD, ID_BATTLE_MENU,
	ID_CARD_STATS, ID_SCORE, ID_COLLECTION, ID_SELL, ID_BUY, ID_BUY_BACK,
	ID_SHOP_HELP, ID_BUY_PRICE, ID_SELL_PRICE, ID_NEED_HELP, ID_MUSIC, ID_SFX,
	ID_CREDITS, ID_DELETE_SLOT_TITLE, ID_DELETE_SLOT_MSG, ID_LANGUAGE,
	ID_BATTLE_END_DRAW, ID_HELP_DECKSELECT1, ID_HELP_DECKSELECT2,
	ID_HELP_DECKSELECT3, ID_HELP_DECKSELECT4, ID_HELP_BATTLE1, ID_HELP_BATTLE2,
	ID_HELP_BATTLE3, ID_HELP_BATTLE4, ID_HELP_BATTLE5, ID_HELP_SHOP1,
	ID_HELP_SHOP2, ID_HELP_SHOP3, ID_HELP_MAIN1, ID_HELP_MAIN2, ID_HELP_MAIN3,
	ID_HELP_MAIN4, ID_HELP_PRESENTATION, ID_HELP_CARDS, ID_OPPONENTS_NAME,
}

const TABLE := [
	# English
	[
		"New", "Enter Player Name", "OK", "Cancel", "Battle", "Shop", "Options",
		"Back", "Play", "Select Five Cards", "Cards", "Favorite Cards",
		"Select Your Opponent", "Select", "Attack", "Type", "P. Defense",
		"M. Defense", "Skip", "Take All", "Up!", "New Attack Type!", "Physical",
		"Magical", "Flexible", "Assault", "Max!",
		"Choose 1 Blue Card as your Prize",
		"You have won all the opponent's Cards!", "Done",
		"The Ai will now choose a defeated Red Card as his Prize",
		"The Ai has won all your Cards...", "MENU", "Card Stats", "Score",
		"Collection", "Sell", "Buy", "Buy Back!",
		"Move a Card to the box below to buy or sell.", "Buy for:", "Sell for:",
		"Need help? Ask the black cat!", "Music:", "SFX:", "Credits",
		"Delete slot data",
		"Are you REALLY sure you want to delete\nALL the data relative to the selected slot?",
		"Language:", "Draw match, press Done to continue.",
		"This is the Deck Select menu. Here you can choose the cards you want use to play.",
		"You can move cards from the Cards list to the Favorite, and vice versa, by dragging them.",
		"Swipe vertically for select the cards type and horizontally for cycle trough the cards.",
		"Drag the cards into these boxes for select them.",
		"Drag the cards in to the grid for play it", "Cards can't be placed here",
		"Opposite remaining cards", "Score", "Card Stats",
		"Move a card here for sell it or buy it", "Your Money",
		"This is the buyable card list. More cards are unlocked by defeating stronger opponents",
		"Fight againts opponents for win new cards, evolve it and unlock stronger foe",
		"Sell cards and buy new one to use it in battle",
		"Watch all your collected cards in full resolution",
		"Change game language and set audio volumes. Don't forget to check out the Credits ^^",
		"Card Master is a collectible cards game, where two opponents fight each other by placing cards in to a 4x4 grid. Every player choose 5 cards of his deck to use. The game end when all the cards are played. The winner is the one that at the end have more cards of his color. The winner player steal one of the captured opponent card.",
		"Cards have 4 stats. Attack (AT), Type (T), Phisical Defense (PD) and Magical Defense (MD). AT, PD and MD value are from 0 to 255, and are subdivided in 16 class from 0 to F. Higher the stats are, higher will be the class. A card can be of 4 Types, Phisical (P), Magical (M), Exploit (X) or Assault (A). Every type define how the card fight againts the other. P attack PD, M attack MD, X attack lowest stats between PD and MD, A use the highest stats of the card to attack the lowest stats of the opponents card, whatever they are. Every crads can have up to 8 arrows, facing the 8 cardinal points. This arrow are used by cards for capture or attack the opponents cards. If a card's arrow face a card without a facing back arrow, the card is automatically captured, but if a card's arrow face a card with a opposite facing back arrow, the fight begin. Stats color, from greens to red, indicate the evolution state of the stats. Red mean the stat is maxed out.",
		"Opponent Name",
	],
	# Italiano
	[
		"Nuovo", "Inserisci il nome del giocatore", "OK", "Annulla", "Battaglia",
		"Negozio", "Opzioni", "Indietro", "Gioca", "Seleziona Cinque Carte",
		"Carte", "Carte Preferite", "Seleziona il Tuo Avversario", "Seleziona",
		"Attacco", "Tipo", "Dif. Fisica", "Dif. Magica", "Skippa", "Prendi Tutte",
		"Up!", "Nuovo Attack Type!", "Fisico", "Magico", "Flessibile", "Assalto",
		"Max!", "Seleziona una Carta Blu come Premio",
		"Hai vinto tutte le carte del tuo avversario!", "Continua",
		"La Ai scegliera' ora una Carta Rossa mMorTa come Premio",
		"La Ai ha vinto tutte le tue carte...", "MENU", "Statistiche Carta",
		"Punti", "Collezione", "Vendi", "Compra", "Ricompra!",
		"Sposta le carte nel riquadro in basso per comprare o vendere.",
		"Compra per:", "Vendi per:", "Serve aiuto? Chiedi al gatto!", "Musica:",
		"Effetti:", "Crediti", "Cancellazione Dati Slot",
		"Sei DAVVERO sicuro di voler cancellare\nTUTTI i dati relativi allo slot selezionato?",
		"Lingua:", "Partita Pareggiata, premi Done per continuare.",
		"Questo é il Deck Menu. Qui puoi scegliere quali carte usare per giocare.",
		"Puoi spostare le carte dalla lista ai preferiti, e vice versa, trascinandole.",
		"Scorri verticalmente per cambiare il tipo di carta e orizzontalmente per scorrere le carte.",
		"Trascina le carte nel riquadro per selezionarle.",
		"Trascina le carte nella griglia per giocarle",
		"Le carte non possno essere giocate sui blocci",
		"Carte rimanenti dell'avversario", "Punteggio", "Statistiche Carta",
		"Posiziona la carta qui per venderla o comprarla", "Monete possedute",
		"Questa é la lista delle carte acquistabili. Si sbloccano nuove carte sconfiggendo avversari piú forti",
		"Combatti gli avversari per conquistare nuove carte, potenziarle e sbloccare nuovi sfidanti",
		"Vendi e compra nuove carte da usare in battaglia",
		"Ammira la tua collezione di carte in alta risoluzione",
		"Cambia la lingua di gioco e modifica i volumi audio. Non dimenticarti di guadare i Crediti ^^",
		"Card Master é un gioco di carte collezionabili, dove 2 avversari si sfidano poszionando delle carte su una griglia 4x4. Ogni giocatore sceglie 5 carte tra tutte quelle possedute. Il gioco termina quando tutte le carte di entrambi i giocatori vengono posizionate. Il vincitore é colui che a fine partita possiede piú carte del suo colore. Il giocatore vincente puó sottrarre all'avversario una carta catturata durante la partita.",
		"Le carte hanno 4 valori. Attacco (AT), Tipo (T), Difesa Fisica (DF) e Difesa Magica (DM). AT, DF e DM hanno valori che vanno tra 0 e 255, suddivisi in 16 classi da 0 a F. Piú il valore e alto, piú la classe sará elevata. Una carta puó essere di 4 tipi, Fisica (F), Magica (M), Exploit (X) e Assalto (A). P attacca DP, M attacca DM, X attacca il valore piú basso tra DP e DM e A usa il valore piú alto della carta per attaccare quello piú basso di quella avversaria. Ogni carta puó avere fino a 8 frecce posizionate sui punti cardinali. Queste frecce vengono utilizzate per catturare o attaccare le carte avversarie. Se la freccia di una carta punta una carta che non ha a sua volta un freccia nella direzione opposta, essa viene automaticamente catturata, altrimenti se c'é una freccia opposta, ha inizio il combattimento. Il colore delle statistiche indica il livello di evoluzione delle stesse. Il colore rosso indica una statistica che ha raggiunto il suo massimo per quel tipo di carta.",
		"Nome del Nemico",
	],
	# 日本語 - full retranslation from English (the reference table was mostly
	# blank placeholders).
	[
		"新規", "プレイヤー名を入力", "OK", "キャンセル", "バトル", "ショップ",
		"オプション", "戻る", "プレイ", "カードを5枚選択", "カード",
		"お気に入りカード", "対戦相手を選択", "選択", "攻撃", "種類", "物理防御",
		"魔法防御", "スキップ", "全て取る", "アップ!", "新しい攻撃タイプ!", "物理",
		"魔法", "柔軟", "強襲", "マックス!", "賞品として青いカードを1枚選んでください",
		"相手のカードを全て獲得しました!", "完了",
		"AIが敗北した赤いカードを賞品として選びます",
		"AIがあなたのカードを全て獲得しました...", "メニュー", "カードステータス",
		"スコア", "コレクション", "売る", "買う", "買い戻す!",
		"カードを下の枠に移動して売買してください。", "購入価格:", "売却価格:",
		"助けが必要?黒猫に聞いてみて!", "音楽:", "効果音:", "クレジット",
		"スロットデータを削除",
		"選択したスロットの\n全てのデータを本当に削除しますか?",
		"言語:", "引き分けです。続けるには完了を押してください。",
		"ここはデッキ選択メニューです。使用したいカードを選ぶことができます。",
		"カードリストとお気に入りの間で、ドラッグしてカードを移動できます。",
		"縦にスワイプでカードの種類を選択、横にスワイプでカードを切り替えます。",
		"カードをこの枠にドラッグして選択してください。",
		"カードをグリッドにドラッグしてプレイします", "ここにはカードを置けません",
		"相手の残りカード", "スコア", "カードステータス",
		"売買するにはカードをここに移動してください", "所持金",
		"これは購入可能なカードのリストです。強い相手を倒すとさらにカードが解放されます",
		"対戦相手と戦って新しいカードを獲得し、進化させて強い敵を解放しよう",
		"カードを売って、バトルで使う新しいカードを買おう",
		"集めたカードを高解像度で鑑賞できます",
		"ゲームの言語変更や音量設定ができます。クレジットも忘れずにチェックしてね^^",
		"「カードマスター」は、2人のプレイヤーが4x4のグリッドにカードを置いて戦うカード収集ゲームです。各プレイヤーはデッキから使用する5枚のカードを選びます。全てのカードが置かれるとゲームは終了します。最終的に自分の色のカードを多く持っている方が勝利です。勝者は捕獲した相手のカードを1枚奪うことができます。",
		"カードには4つのステータスがあります。攻撃力(AT)、タイプ(T)、物理防御力(PD)、魔法防御力(MD)です。AT、PD、MDの値は0〜255で、0〜Fの16段階に分けられます。数値が高いほどクラスも高くなります。カードには物理(P)、魔法(M)、万能(X)、強襲(A)の4つのタイプがあり、タイプによって戦い方が決まります。Pの攻撃はPDを、Mの攻撃はMDを狙います。XはPDとMDのうち低い方を狙い、Aはカードの最も高いステータスで相手の最も低いステータスを攻撃します。カードには8方向に矢印を最大8個まで持てます。この矢印は相手のカードを捕獲したり攻撃したりするために使われます。矢印が反対方向の矢印を持たないカードを指している場合、そのカードは自動的に捕獲されます。逆に反対方向に矢印があると戦闘が始まります。ステータスの色は緑から赤へと進化状態を示し、赤は最大値に達したことを意味します。",
		"対戦相手の名前",
	],
]

func get_string(id: int) -> String:
	return TABLE[Game.language][id]
